### ISSUE TITLE
Would multiple identities be necessary if various nicknames for users were hidden?

### ISSUE THREAD

**Issue by trosel** [ssbc/ssb-identities#8]
https://github.com/ssbc/scuttlebutt.nz/issues/145

One identity could be more manageable if nicknames were limited in visibility to only the person that gave you the nickname.

**Comment by dominictarr** [comment]
no, because it would be obvious that the identity was the same person, because they would have the same key. You can't hide the key because it's a part of the protocol.

**Comment by trosel** [comment]
Ah yes. I guess I'm thinking of a different use case than you are.
